{/* List of error codes */}
const ERROR_CODES = {
  INVALID_EVENT_TYPE: "INVALID_EVENT_TYPE",
  PASSWORD_ALREADY_USED: "PASSWORD_ALREADY_USED",
  USER_IN_RECOVERY_MODE: "USER_IN_RECOVERY_MODE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CONTENT_ALREADY_EXIST: "CONTENT_ALREADY_EXIST",
  REQUIRED_PARAMETER: "REQUIRED_PARAMETER",
  INVALID_CONTENT: "INVALID_CONTENT",
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",
  DOESNT_HAVE_PERMISSION: "DOESNT_HAVE_PERMISSION",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  MISSING_TOKEN: "MISSING_TOKEN",
};
const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

export { ERROR_CODES, STATUS_CODES };
